# stages:
#   - build
#   - test
#   - docker
#   - deploy

# variables:
#   IMAGE_NAME: $DOCKER_USERNAME/devops-app

# # -------------------
# # BUILD
# # -------------------
# build:
#   stage: build
#   image: node:18
#   script:
#     - npm install
#     - echo "Build complete"

# # -------------------
# # TEST
# # -------------------
# test:
#   stage: test
#   image: node:18
#   script:
#     - npm test

# # -------------------
# # DOCKER BUILD + PUSH
# # -------------------
# docker-build:
#   stage: docker
#   image: docker:latest
#   services:
#     - docker:dind
#   script:
#     - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#     - docker build -t $IMAGE_NAME .
#     - docker push $IMAGE_NAME

# # -------------------
# # DEPLOY
# # -------------------
# deploy:
#   stage: deploy
#   image: docker:latest
#   script:
#     - docker stop devops-container || true
#     - docker rm devops-container || true
#     - docker pull $IMAGE_NAME
#     - docker run -d -p 6000:6000 --name devops-container $IMAGE_NAME







stages:
  - build
  - test
  - docker
  - deploy

variables:
  IMAGE_NAME: $DOCKER_USERNAME/devops-app
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

# -------------------
# BUILD
# -------------------
build:
  stage: build
  image: node:18
  script:
    - npm install
    - echo "Build complete"

# -------------------
# TEST
# -------------------
test:
  stage: test
  image: node:18
  script:
    - npm test

# -------------------
# DOCKER BUILD + PUSH
# -------------------
docker-build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind   # ✅ IMPORTANT
  script:
    - docker info   # test connection
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME

# -------------------
# DEPLOY
# -------------------
deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind   # ✅ REQUIRED HERE ALSO
  script:
    - docker stop devops-container || true
    - docker rm devops-container || true
    - docker pull $IMAGE_NAME
    - docker run -d -p 6000:6000 --name devops-container $IMAGE_NAME